src/objects/Agency_Billing_Run__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <summarizedField>Xero_Invoice__c.Amount__c</summarizedField>
        <summaryForeignKey>Xero_Invoice__c.Agency_Billing_Run__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Agency Billing Run</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Agency Billing Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Billing Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agency_Campaign__c.object
<CustomObject>
    <description>Tracking the campaigns that connect Brands to Agencies and Retailers</description>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Agency/Platform</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Campaigns (Agency)</relationshipLabel>
        <relationshipName>Agency_Campaigns1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Campaigns__c</fullName>
        <label>Number of Campaigns</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Agency Campaign</label>
    <nameField>
        <label>Agency Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Xero_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Agecny__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Xero Invoices</relationshipLabel>
        <relationshipName>Xero_Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Billing_Run__c</fullName>
        <label>Agency Billing Run</label>
        <referenceTo>Agency_Billing_Run__c</referenceTo>
        <relationshipLabel>Xero Invoices</relationshipLabel>
        <relationshipName>Xero_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <summarizedField>Xero_Invoice_Line__c.Amount__c</summarizedField>
        <summaryForeignKey>Xero_Invoice_Line__c.Xero_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <externalId>true</externalId>
        <label>Xero ID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Xero Invoice</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Xero Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Xero_Invoice_Line__c.object
<CustomObject>
    <description>Xero Importable Data</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Xero Invoice Lines</relationshipLabel>
        <relationshipName>Xero_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agency Campaign</label>
        <referenceTo>Agency_Campaign__c</referenceTo>
        <relationshipLabel>Xero Invoice Lines</relationshipLabel>
        <relationshipName>Xero_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Unit_Amount__c * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Amount__c</fullName>
        <label>Unit Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice__c</fullName>
        <label>Xero Invoice</label>
        <referenceTo>Xero_Invoice__c</referenceTo>
        <relationshipLabel>Xero Invoice Lines</relationshipLabel>
        <relationshipName>Xero_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Xero Invoice Line</label>
    <nameField>
        <displayFormat>X-{0000000}</displayFormat>
        <label>Xero Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestExportInvoice2Xero.cls
@istest
public class TestExportInvoice2Xero {
    @isTest Static void ExportInvoice() {
        Test.startTest();
     
        id r = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency/Platform').getRecordTypeId();
        Account a1 = new Account(name='----Agency Test Account Invoice Separate',RecordTypeId =r, Invoice_Per_Campaign__c=true, Xero_Id__c='fa3cccca-d919-405c-acae-123e7ae2fed9');
        insert a1;
        Agency_Billing_run__c run = new Agency_Billing_run__c(Invoice_date__c =Date.today(),Start_date__c=Date.today(), End_date__c=Date.today() );
        insert run;
        Agency_Campaign__c ac = new Agency_Campaign__c(Name='---test---test--', Start_Date__c=Date.today(), Agency__c=a1.id,  Number_of_Campaigns__c =1 );
        insert ac;
        Xero_Invoice__c i = new  Xero_Invoice__c(Invoice_Date__c=Date.today(),Agecny__c=a1.id, Agency_Billing_run__c=run.id);
        insert i;
        Xero_invoice_Line__c il = new Xero_invoice_line__c(Account__c=a1.id,Agency_Campaign__c=ac.id,Xero_Invoice__c=i.id,Unit_amount__c=100, Quantity__c=1,Description__c='Test description');
        insert il;
 //       List<Xero_Invoice__c> iList = [SELECT name,Invoice_Date__c,Amount__c,Xero_ID__c, Agecny__r.name, Agecny__r.Xero_Id__c FROM Xero_Invoice__c WHERE Xero_ID__c=''];
//                list<Xero_Invoice_Line__c> li = [SELECT Amount__c , Quantity__c, Description__c, Unit_Amount__c  FROM Xero_Invoice_Line__c WHERE Xero_Invoice__c	=:inv.id 	];

        ExportInvoice2Xero.Export();
        Test.stopTest();
 
    }
    
}