src/objects/Agency_Billing_Run__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sync_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Trigger Sync</inlineHelpText>
        <label>Sync_Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Agency Billing Run</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Agency Billing Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Billing Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agency_Campaign__c.object
<CustomObject>
    <description>Tracking the campaigns that connect Brands to Agencies and Retailers</description>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Agency/Platform</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Campaigns (Agency)</relationshipLabel>
        <relationshipName>Agency_Campaigns1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Campaigns (Account)</relationshipLabel>
        <relationshipName>Agency_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Date__c</fullName>
        <label>Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Campaigns__c</fullName>
        <label>Number of Campaigns</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SmartSuite__c</fullName>
        <externalId>true</externalId>
        <label>SmartSuite ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Weekly_Rate__c</fullName>
        <description>Rate for weeks above max weeks</description>
        <label>Weekly Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Agency Campaign</label>
    <nameField>
        <label>Agency Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestsForAgencyCampaign.cls
@istest
public class TestsForAgencyCampaign {
    @isTest static void TestInsertTrigger() {
        Test.startTest();
        
        // Test data setup
        // Create an account with an opportunity, and then try to delete it
        id r = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency/Platform').getRecordTypeId();
        Account a = new Account(name='----Agency Test Account',RecordTypeId =r, Rate__c=2500,Weekly_rate__c	=250, Max_Length__c=6 );
        insert a;
        Agency_Campaign__c ac = new Agency_Campaign__c(Name='---test---test--', Start_Date__c=Date.today(), Agency__c=a.id, Number_of_Campaigns__c =1 );
        // Perform test
        insert ac;
        Test.stopTest();
        Agency_Campaign__c check = [SELECT billing_date__c FROM Agency_Campaign__c WHERE id = :ac.id];
        System.debug( check.billing_date__c );
        System.assert(check.billing_date__c==eom(Date.today()));
    }
    private static date eom(date d) {   
        return   Date.newInstance(d.year(), d.month(), Date.daysInMonth(d.year(), d.month()));  
    }
    
    @isTest Static void createInvoice() {
        Test.startTest();
        
        id r = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Agency/Platform').getRecordTypeId();
        Account a1 = new Account(name='----Agency Test Account Invoice Separate',RecordTypeId =r, Invoice_Per_Campaign__c=true);
        insert a1;
        Account a2 = new Account(name='----Agency Test Account Combo',RecordTypeId =r,Invoice_Per_Campaign__c=false);
        insert a2;
      //  Account a3 = new Account(name='----Agency Test Bill As Account',RecordTypeId =r,Invoice_Per_Campaign__c=false, AccountNumber='123' );
      //  insert a3;
        
        Agency_Campaign__c ac1 = new Agency_Campaign__c(SmartSuite__c='#1',Name='---test---test--1', Number_of_Campaigns__c =1,Start_Date__c=Date.today(), Agency__c=a1.id );
        Agency_Campaign__c ac2 = new Agency_Campaign__c(SmartSuite__c='#2',Name='---test---test--2', Number_of_Campaigns__c =1,Start_Date__c=Date.today(), Agency__c=a2.id );
        Agency_Campaign__c ac3 = new Agency_Campaign__c(Billing_Account__c=a1.id, SmartSuite__c='#3',Name='---test---test--3', Number_of_Campaigns__c =1,Start_Date__c=Date.today(), Agency__c=a2.id );

        insert ac1;
        insert ac2;
        insert ac3;

        Agency_Billing_run__c run = new Agency_Billing_run__c(Invoice_Date__c = eom(Date.today()), End_date__c=eom(Date.today()), Start_date__c=Date.today() );
        insert run;
        //AgencyInvoicing.CreateInvoices(run.id);
        run.Sync_Trigger__c = true;
        update run; // now test the update trigger.
        Test.stopTest();
        
    }
}