src/objects/Agency_Billing_Run__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Agency Billing Run</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Agency Billing Run Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agency Billing Runs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Agency_Campaign__c.object
<CustomObject>
    <description>Tracking the campaigns that connect Brands to Agencies and Retailers</description>
    <fields>
        <fullName>Agency_Rate__c</fullName>
        <formula>IF(!(Rate__c=0),Rate__c,Agency__r.Rate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agency Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Agency/Platform</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agency Campaigns (Agency)</relationshipLabel>
        <relationshipName>Agency_Campaigns1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bill_Extra_Weeks__c</fullName>
        <formula>if(Weekly_Rate__c&gt;0,Floor(Weeks__c-Max_Weeks__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bill Extra Weeks</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Date__c</fullName>
        <label>Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description_for_Invoice__c</fullName>
        <formula>"Campaign #" &amp;SmartSuite__c &amp;" "&amp; TRIM(Billing_ID_PO__c &amp; " ") &amp; " - " &amp; Brands__c &amp;  " - " &amp; TEXT( Number_of_Campaigns__c ) &amp; " Campaign(s); Media Type: " &amp; 
IF(INCLUDES( Media__c, "Social"), "Social Network; ", "") &amp; 
IF(INCLUDES( Media__c, "Influencer"), "Influencer; ", "") &amp; 
IF(INCLUDES( Media__c, "Mobile in-app"), "Mobile in-app; ", "") &amp; 
IF(INCLUDES( Media__c, "Print ad"), "Print ad; ", "") &amp; 
IF(INCLUDES( Media__c, "Programmatic"), "Programmatic; ", "") &amp; 
IF(INCLUDES( Media__c, "Native"), "Native", "") &amp; 
IF(INCLUDES( Media__c , "Email"), "Email; ", "") &amp;
IF(INCLUDES( Media__c , "Website"), "Website; ", "") &amp;
IF(INCLUDES( Media__c , "QR Code"), "QR Code; ", "") &amp;
IF(INCLUDES( Media__c , "Display"), "Display; ", "") &amp;
IF(INCLUDES( Media__c , "Chatbot"), "Chatbot; ", "") &amp;
IF(INCLUDES( Media__c , "YouTube"), "YouTube; ", "") &amp;
IF(INCLUDES( Media__c , "Video"), "Video; ", "") &amp;
IF(INCLUDES( Media__c , "Website"), "Website; ", "") &amp;
IF(INCLUDES( Media__c , "Other"), "Other; ", "") &amp;
 "Retailer: "  &amp; TRIM( SUBSTITUTE( Retailer_s__c,","," ") ) &amp;
 "; Launch date: " &amp;  TEXT(Start_Date__c)&amp;br()&amp;
Bill_as__c &amp; br() &amp;
Cost_Notes_Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description for Invoice</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoiced__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Has been invoiced?</description>
        <label>Invoiced?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Weeks__c</fullName>
        <label>Max Weeks</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Campaigns__c</fullName>
        <label>Number of Campaigns</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SmartSuite__c</fullName>
        <externalId>true</externalId>
        <label>SmartSuite ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Weekly_Rate__c</fullName>
        <description>Rate for weeks above max weeks</description>
        <label>Weekly Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Weeks__c</fullName>
        <formula>(End_Date__c -  Start_Date__c)/7</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Weeks</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Agency Campaign</label>
    <nameField>
        <label>Agency Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Xero_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Agecny__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Xero Invoices</relationshipLabel>
        <relationshipName>Xero_Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Billing_Run__c</fullName>
        <label>Agency Billing Run</label>
        <referenceTo>Agency_Billing_Run__c</referenceTo>
        <relationshipLabel>Xero Invoices</relationshipLabel>
        <relationshipName>Xero_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Xero Invoice</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Xero Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Xero_Invoice_Line__c.object
<CustomObject>
    <description>Xero Importable Data</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Xero Invoice Lines</relationshipLabel>
        <relationshipName>Xero_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_Campaign__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agency Campaign</label>
        <referenceTo>Agency_Campaign__c</referenceTo>
        <relationshipLabel>Xero Invoice Lines</relationshipLabel>
        <relationshipName>Xero_Invoice_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Amount__c</fullName>
        <label>Unit Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice__c</fullName>
        <label>Xero Invoice</label>
        <referenceTo>Xero_Invoice__c</referenceTo>
        <relationshipLabel>Xero Invoice Lines</relationshipLabel>
        <relationshipName>Xero_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Xero Invoice Line</label>
    <nameField>
        <displayFormat>X-{0000000}</displayFormat>
        <label>Xero Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreatingInvoicesBatch.cls
global class CreatingInvoicesBatch implements Database.Batchable<sObject>  {  
    
     date InvoiceDate;
     Agency_Billing_Run__c run2;
     date BillingStart;
     date BillingEnd;

     global CreatingInvoicesBatch(string	 rname){
        run2 = [select id, Description__c,Invoice_Date__c, End_date__c, Start_date__c from Agency_billing_run__c where name=:rname];   
     }    
    
     global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator( [select id, Description__c,Invoice_Date__c, End_date__c, Start_date__c  from Agency_billing_run__c where id=:run2.id]);
    }
    
    global void finish(Database.BatchableContext BC)
    {     }
    
    global void execute(Database.BatchableContext BC, List<Agency_Billing_Run__c> run ) {
        BillingStart = run2.Start_date__c ;
        BillingEnd   = run2.End_date__c;
        InvoiceDate  = run2.Invoice_Date__c;  
        
        List<AggregateResult>  accts = [SELECT a.id, COUNT(Number_of_Campaigns__c) FROM Agency_campaign__c c, c.Agency__r a WHERE (billing_date__c >=:BillingStart AND billing_date__c <=:BillingEnd AND Invoiced__c=FALSE ) GROUP by a.id ];
        if (!accts.isEmpty()) { 
           // run = newRun(InvoiceDate); // create the batch hold record - will allow a delete and redo
            
            for (AggregateResult a : accts) {   
                
                Account Agency = [SELECT Name, invoice_per_campaign__c FROM Account WHERE id=:a.id ];
                System.debug('Agency '+Agency.name);
                List<Agency_Campaign__c> cps = [SELECT id,name,SmartSuite__c,Description_for_Invoice__c,Agency__c,Number_of_Campaigns__c,Agency_Rate__c,Weekly_Rate__c, Max_Weeks__c,Weeks__c,Bill_extra_weeks__c  FROM Agency_campaign__c c  WHERE (Agency__c=:a.id AND billing_date__c >=:BillingStart AND billing_date__c <=:BillingEnd AND Invoiced__c=FALSE ) ];
                
                if (Agency.Invoice_Per_Campaign__c) {  
                    
                    for (Agency_Campaign__c c : cps) {
                        
                        Xero_Invoice__c inv = CreateXeroInvoice(Agency.id);
                        Xero_Invoice_line__c line = CreateXeroInvoiceLine( inv,  c );
                        System.debug('Invoice -'+inv.name+' - '+c.name+' '+c.Description_for_Invoice__c+' ' );
                    }  
                } else {
                    Xero_Invoice__c inv = CreateXeroInvoice(Agency.id);
                    for (Agency_Campaign__c c : cps) {
                        Xero_Invoice_line__c line = CreateXeroInvoiceLine( inv,  c );
                        
                        System.debug('Invoice '+inv.name+' - '+c.name+' '+c.Description_for_Invoice__c+' ' );
                    }  
                    
                }
            }
        }
    }
    global Xero_Invoice__c CreateXeroInvoice(string ac) {
        Xero_Invoice__c inv = new Xero_Invoice__c(Agecny__c  = ac, invoice_date__c = InvoiceDate, Agency_Billing_Run__c = run2.id );
        insert inv;
        return inv;
    }
    
    global Xero_Invoice_Line__c CreateXeroInvoiceLine(Xero_Invoice__c inv, Agency_Campaign__c c ) {
      System.debug( c.Agency_Rate__c );
       System.debug(c.Bill_Extra_Weeks__c );
                     System.debug( c.Weekly_Rate__c );
                    
        if (c.Weekly_Rate__c==null) {c.Weekly_Rate__c=0;}
        Xero_Invoice_Line__c l = new Xero_Invoice_Line__c( Account__c   = c.Agency__c, Xero_invoice__c= inv.Id, Agency_Campaign__c=c.Id, Quantity__c = c.Number_of_Campaigns__c, Unit_Amount__c = c.Agency_Rate__c +c.Bill_Extra_Weeks__c*c.Weekly_Rate__c , Description__c= c.Description_for_Invoice__c );
        insert l;
        return l;
    }
    
/**  static Agency_Billing_Run__c newRun(date d) {
        Agency_Billing_Run__c b	= new Agency_Billing_Run__c(End_Date__c = BillingEnd, Start_Date__c = BillingStart);
       insert b;
       return b;

    } 
*/  

}