src/objects/Xero_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Agecny__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Xero Invoices</relationshipLabel>
        <relationshipName>Xero_Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <summarizedField>Xero_Invoice_Line__c.Amount__c</summarizedField>
        <summaryForeignKey>Xero_Invoice_Line__c.Xero_Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Xero_ID__c</fullName>
        <externalId>true</externalId>
        <label>Xero ID</label>
        <length>36</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Xero Invoice</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Xero Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Xero_Invoice_Line__c.object
<CustomObject>
    <description>Xero Importable Data</description>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Unit_Amount__c * Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>7</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Amount__c</fullName>
        <label>Unit Amount</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Xero_Invoice__c</fullName>
        <label>Xero Invoice</label>
        <referenceTo>Xero_Invoice__c</referenceTo>
        <relationshipLabel>Xero Invoice Lines</relationshipLabel>
        <relationshipName>Xero_Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Xero Invoice Line</label>
    <nameField>
        <displayFormat>X-{0000000}</displayFormat>
        <label>Xero Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xero Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExportInvoice2Xero.cls
public class ExportInvoice2Xero {
      public static void wait(Integer Seconds) {
        Long startingTime = System.now().getTime(); // Num milliseconds since Jan 1 1970
        Integer delayInMilliseconds = 1000*Seconds; // One-second delay
        while (System.now().getTime() - startingTime < delayInMilliseconds)  {
            // Do nothing until desired delay has passed
        }
    }  
    
  public static void Export() {
        List<Xero_Invoice__c> iList = [SELECT name,Invoice_Date__c,Amount__c,Xero_ID__c, Agecny__r.name, Agecny__r.Xero_Id__c FROM Xero_Invoice__c WHERE Xero_ID__c=''];
        list<XeroInvoice> xiList;
        Integer i = 0;
        for (Xero_Invoice__c inv  : iList) {
            System.debug(inv.name+'->'+inv.Agecny__r.Xero_Id__c);
            if (!(String.isBlank(inv.Agecny__r.Xero_Id__c))) {
                XeroInvoice xi = new XeroInvoice(inv.Agecny__r.Xero_Id__c); 
                xi.Date_x =dstring( inv.Invoice_Date__c)  ;	 //2019-08-20T00:00:00             
                xi.DueDate=dstring( (inv.Invoice_Date__c +30) ) ; //2019-08-20T00:00:00
                xi.LineAmountTypes = 'Exclusive';
                xi.InvoiceNumber = inv.name;
                xi.status = 'AUTHORISED';
                list<Xero_Invoice_Line__c> li = [SELECT Amount__c , Quantity__c, Description__c, Unit_Amount__c  FROM Xero_Invoice_Line__c WHERE Xero_Invoice__c	=:inv.id 	];
                xi.LineItems = new List<XeroInvoice.LineItem>();
                for (Xero_Invoice_line__c ll : li) {
                    XeroInvoice.LineItem lineI = new XeroInvoice.LineItem( );
                    lineI.AccountCode = '41001';
                    lineI.Description = ll.Description__c;
                    lineI.Quantity = ll.Quantity__c;
                    lineI.LineAmount = ll.Amount__c;
                    System.debug(LineI);         
                    xi.LineItems.add(lineI  );
                }
                XeroInvoice rt;
                if (test.isRunningTest()) {
                    rt = xi;
                } else {
                    rt = XeroAPI.sendInvoice( xi ); 
                }
                System.debug(xi);
                inv.Xero_ID__c = rt.InvoiceID;
                update inv;
                Wait(1);

            }
        }
    }
    
    public static string dstring(date d) {
        return d.year() + '-' + d.month() + '-' + d.day()+'T00:00:00';
    }
    
}